//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 06:17:30 PM CST 
//


package com.choice.hotels;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.choice.hotels package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.choice.hotels
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetHotelByIdRequest }
     * 
     */
    public GetHotelByIdRequest createGetHotelByIdRequest() {
        return new GetHotelByIdRequest();
    }

    /**
     * Create an instance of {@link GetHotelByIdResponse }
     * 
     */
    public GetHotelByIdResponse createGetHotelByIdResponse() {
        return new GetHotelByIdResponse();
    }

    /**
     * Create an instance of {@link HotelInfo }
     * 
     */
    public HotelInfo createHotelInfo() {
        return new HotelInfo();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link CreateHotelRequest }
     * 
     */
    public CreateHotelRequest createCreateHotelRequest() {
        return new CreateHotelRequest();
    }

    /**
     * Create an instance of {@link CreateHotelResponse }
     * 
     */
    public CreateHotelResponse createCreateHotelResponse() {
        return new CreateHotelResponse();
    }

    /**
     * Create an instance of {@link UpdateHotelRequest }
     * 
     */
    public UpdateHotelRequest createUpdateHotelRequest() {
        return new UpdateHotelRequest();
    }

    /**
     * Create an instance of {@link UpdateHotelResponse }
     * 
     */
    public UpdateHotelResponse createUpdateHotelResponse() {
        return new UpdateHotelResponse();
    }

    /**
     * Create an instance of {@link DeleteHotelRequest }
     * 
     */
    public DeleteHotelRequest createDeleteHotelRequest() {
        return new DeleteHotelRequest();
    }

    /**
     * Create an instance of {@link DeleteHotelResponse }
     * 
     */
    public DeleteHotelResponse createDeleteHotelResponse() {
        return new DeleteHotelResponse();
    }

    /**
     * Create an instance of {@link GetAllHotelsByNameRequest }
     * 
     */
    public GetAllHotelsByNameRequest createGetAllHotelsByNameRequest() {
        return new GetAllHotelsByNameRequest();
    }

    /**
     * Create an instance of {@link GetAllHotelsByNameResponse }
     * 
     */
    public GetAllHotelsByNameResponse createGetAllHotelsByNameResponse() {
        return new GetAllHotelsByNameResponse();
    }

    /**
     * Create an instance of {@link AddAmenityRequest }
     * 
     */
    public AddAmenityRequest createAddAmenityRequest() {
        return new AddAmenityRequest();
    }

    /**
     * Create an instance of {@link AddAmenityResponse }
     * 
     */
    public AddAmenityResponse createAddAmenityResponse() {
        return new AddAmenityResponse();
    }

    /**
     * Create an instance of {@link AmenityInfo }
     * 
     */
    public AmenityInfo createAmenityInfo() {
        return new AmenityInfo();
    }

    /**
     * Create an instance of {@link DeleteAmenityRequest }
     * 
     */
    public DeleteAmenityRequest createDeleteAmenityRequest() {
        return new DeleteAmenityRequest();
    }

    /**
     * Create an instance of {@link DeleteAmenityResponse }
     * 
     */
    public DeleteAmenityResponse createDeleteAmenityResponse() {
        return new DeleteAmenityResponse();
    }

}
